// Generated by gencpp from file arm_lib/forwardKinematics.msg
// DO NOT EDIT!


#ifndef ARM_LIB_MESSAGE_FORWARDKINEMATICS_H
#define ARM_LIB_MESSAGE_FORWARDKINEMATICS_H

#include <ros/service_traits.h>


#include <arm_lib/forwardKinematicsRequest.h>
#include <arm_lib/forwardKinematicsResponse.h>


namespace arm_lib
{

struct forwardKinematics
{

typedef forwardKinematicsRequest Request;
typedef forwardKinematicsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct forwardKinematics
} // namespace arm_lib


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm_lib::forwardKinematics > {
  static const char* value()
  {
    return "198c0d7b1e734c5386527504b3803cdd";
  }

  static const char* value(const ::arm_lib::forwardKinematics&) { return value(); }
};

template<>
struct DataType< ::arm_lib::forwardKinematics > {
  static const char* value()
  {
    return "arm_lib/forwardKinematics";
  }

  static const char* value(const ::arm_lib::forwardKinematics&) { return value(); }
};


// service_traits::MD5Sum< ::arm_lib::forwardKinematicsRequest> should match
// service_traits::MD5Sum< ::arm_lib::forwardKinematics >
template<>
struct MD5Sum< ::arm_lib::forwardKinematicsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm_lib::forwardKinematics >::value();
  }
  static const char* value(const ::arm_lib::forwardKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_lib::forwardKinematicsRequest> should match
// service_traits::DataType< ::arm_lib::forwardKinematics >
template<>
struct DataType< ::arm_lib::forwardKinematicsRequest>
{
  static const char* value()
  {
    return DataType< ::arm_lib::forwardKinematics >::value();
  }
  static const char* value(const ::arm_lib::forwardKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm_lib::forwardKinematicsResponse> should match
// service_traits::MD5Sum< ::arm_lib::forwardKinematics >
template<>
struct MD5Sum< ::arm_lib::forwardKinematicsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm_lib::forwardKinematics >::value();
  }
  static const char* value(const ::arm_lib::forwardKinematicsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_lib::forwardKinematicsResponse> should match
// service_traits::DataType< ::arm_lib::forwardKinematics >
template<>
struct DataType< ::arm_lib::forwardKinematicsResponse>
{
  static const char* value()
  {
    return DataType< ::arm_lib::forwardKinematics >::value();
  }
  static const char* value(const ::arm_lib::forwardKinematicsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_LIB_MESSAGE_FORWARDKINEMATICS_H
