// Generated by gencpp from file arm_lib/inverseKinematics.msg
// DO NOT EDIT!


#ifndef ARM_LIB_MESSAGE_INVERSEKINEMATICS_H
#define ARM_LIB_MESSAGE_INVERSEKINEMATICS_H

#include <ros/service_traits.h>


#include <arm_lib/inverseKinematicsRequest.h>
#include <arm_lib/inverseKinematicsResponse.h>


namespace arm_lib
{

struct inverseKinematics
{

typedef inverseKinematicsRequest Request;
typedef inverseKinematicsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct inverseKinematics
} // namespace arm_lib


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm_lib::inverseKinematics > {
  static const char* value()
  {
    return "2c802ecf38b17c9f65562f8dd1868972";
  }

  static const char* value(const ::arm_lib::inverseKinematics&) { return value(); }
};

template<>
struct DataType< ::arm_lib::inverseKinematics > {
  static const char* value()
  {
    return "arm_lib/inverseKinematics";
  }

  static const char* value(const ::arm_lib::inverseKinematics&) { return value(); }
};


// service_traits::MD5Sum< ::arm_lib::inverseKinematicsRequest> should match
// service_traits::MD5Sum< ::arm_lib::inverseKinematics >
template<>
struct MD5Sum< ::arm_lib::inverseKinematicsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm_lib::inverseKinematics >::value();
  }
  static const char* value(const ::arm_lib::inverseKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_lib::inverseKinematicsRequest> should match
// service_traits::DataType< ::arm_lib::inverseKinematics >
template<>
struct DataType< ::arm_lib::inverseKinematicsRequest>
{
  static const char* value()
  {
    return DataType< ::arm_lib::inverseKinematics >::value();
  }
  static const char* value(const ::arm_lib::inverseKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm_lib::inverseKinematicsResponse> should match
// service_traits::MD5Sum< ::arm_lib::inverseKinematics >
template<>
struct MD5Sum< ::arm_lib::inverseKinematicsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm_lib::inverseKinematics >::value();
  }
  static const char* value(const ::arm_lib::inverseKinematicsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_lib::inverseKinematicsResponse> should match
// service_traits::DataType< ::arm_lib::inverseKinematics >
template<>
struct DataType< ::arm_lib::inverseKinematicsResponse>
{
  static const char* value()
  {
    return DataType< ::arm_lib::inverseKinematics >::value();
  }
  static const char* value(const ::arm_lib::inverseKinematicsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_LIB_MESSAGE_INVERSEKINEMATICS_H
